#!/usr/bin/env python
"""
Utility script for administrative tasks.

This script is part of the example factory dashboard.  It mirrors the
standard `manage.py` file generated by the `django-admin startproject`
command, allowing commands such as `runserver` or `makemigrations` when
Django is installed.  The script is included here for completeness,
although running the dashboard in this sample project is optional for
students reviewing the code structure.
"""
import os
import sys


def main() -> None:
    """Run administrative tasks."""
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "factory_dashboard.settings")
    try:
        from django.core.management import execute_from_command_line  # type: ignore
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Make sure it is installed and available on your PYTHONPATH environment variable. "
            "See https://docs.djangoproject.com/ for instructions."
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()